# Generated by Django 4.0.3 on 2022-04-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='文章标题')),
                ('post_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='发布时间')),
                ('source', models.CharField(blank=True, max_length=64, null=True, verbose_name='文章来源')),
                ('tags', models.JSONField(blank=True, help_text='文章标签', null=True, verbose_name='文章标签')),
                ('content', models.TextField(blank=True, help_text='文章内容', null=True, verbose_name='文章内容')),
                ('count', models.IntegerField(default=0, verbose_name='阅读数')),
                ('status', models.BooleanField(default=True, help_text='文章状态，True为正常，False为禁用', verbose_name='文章状态')),
            ],
            options={
                'verbose_name': '文章表',
                'verbose_name_plural': '文章表',
                'db_table': 'easydo_article',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='文章分类名')),
                ('ordering', models.IntegerField(default=0, help_text='号大优先，同号者id小优先', verbose_name='排序')),
            ],
            options={
                'verbose_name': '文章分类表',
                'verbose_name_plural': '文章分类表',
                'db_table': 'easydo_article_category',
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReadingRecord',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('article', models.ForeignKey(blank=True, db_column='article', db_constraint=False, help_text='文章', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article', verbose_name='文章')),
                ('article_cate', models.ForeignKey(blank=True, db_column='acate', db_constraint=False, help_text='对应文章分类', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecategory', verbose_name='对应文章分类')),
            ],
            options={
                'verbose_name': '用户阅读记录表',
                'verbose_name_plural': '用户阅读记录表',
                'db_table': 'easydo_reading_record',
                'ordering': ('-id',),
            },
        ),
    ]
