# Generated by Django 4.0.3 on 2022-04-17 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrecord',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', db_constraint=False, help_text='用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', db_constraint=False, help_text='文章分类', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecategory', verbose_name='文章分类'),
        ),
    ]
